apiVersion: apps/v1
kind: Deployment
metadata:
  name: demobox
  labels:
    app: demobox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demobox
  template:
    metadata:
      labels:
        app: demobox
    spec:
      hostNetwork: true
      dnsPolicy: Default  # hostDNS is required for demobox to access the database
      imagePullSecrets:
        - name: acr-secret
      volumes:
        - name: data
          hostPath:
            path: /data0
            type: DirectoryOrCreate
      containers:
        - name: demobox
          image: registry.cn-hangzhou.aliyuncs.com/snowbo/demobox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            # Database (required for auth & archive API)
            - name: SNOWBO_DB_URL
              value: "{mysql_host}"
            - name: SNOWBO_DB_PORT
              value: "{mysql_port}"
            - name: SNOWBO_DB_USER
              value: "{mysql_user}"
            - name: SNOWBO_DB_PASSWD
              value: "{mysql_password}"
            - name: SNOWBO_DB_NAME
              value: "{mysql_database}"
            - name: SNOWBO_STORAGE_ROOTPATH
              value: "/data"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5