// iconpack turns the canonical sandbox PNG into the Windows resources used by
// the local executable. It intentionally uses only the Go standard library so
// release packaging does not depend on an external resource compiler.
package main

import (
	"bytes"
	"encoding/binary"
	"flag"
	"fmt"
	"image"
	_ "image/jpeg"
	"image/png"
	"io"
	"os"
	"path/filepath"
)

var sizes = []int{16, 20, 24, 32, 40, 48, 64, 128, 256}

type iconImage struct {
	size int
	png  []byte
}

func main() {
	input := flag.String("input", "frontend/public/logo/sandbox-icon.png", "source PNG")
	icoOut := flag.String("ico", "assets/sandbox-icon.ico", "output ICO")
	rsrcOut := flag.String("rsrc", "cmd/local/rsrc_windows_amd64.syso", "output Windows resource object")
	flag.Parse()

	file, err := os.Open(*input)
	fatalIf(err)
	defer file.Close()
	source, _, err := image.Decode(file)
	fatalIf(err)

	icons := make([]iconImage, 0, len(sizes))
	for _, size := range sizes {
		resized := image.NewNRGBA(image.Rect(0, 0, size, size))
		bounds := source.Bounds()
		for y := 0; y < size; y++ {
			for x := 0; x < size; x++ {
				sx := bounds.Min.X + x*bounds.Dx()/size
				sy := bounds.Min.Y + y*bounds.Dy()/size
				resized.Set(x, y, source.At(sx, sy))
			}
		}
		var encoded bytes.Buffer
		fatalIf(png.Encode(&encoded, resized))
		icons = append(icons, iconImage{size: size, png: encoded.Bytes()})
	}

	fatalIf(writeICO(*icoOut, icons))
	fatalIf(writeResourceObject(*rsrcOut, icons))
}

func writeICO(path string, icons []iconImage) error {
	var out bytes.Buffer
	fatalIf(binary.Write(&out, binary.LittleEndian, uint16(0)))
	fatalIf(binary.Write(&out, binary.LittleEndian, uint16(1)))
	fatalIf(binary.Write(&out, binary.LittleEndian, uint16(len(icons))))
	offset := uint32(6 + len(icons)*16)
	for _, icon := range icons {
		width, height := byte(icon.size), byte(icon.size)
		if icon.size == 256 {
			width, height = 0, 0
		}
		out.WriteByte(width)
		out.WriteByte(height)
		out.WriteByte(0)
		out.WriteByte(0)
		fatalIf(binary.Write(&out, binary.LittleEndian, uint16(1)))
		fatalIf(binary.Write(&out, binary.LittleEndian, uint16(32)))
		fatalIf(binary.Write(&out, binary.LittleEndian, uint32(len(icon.png))))
		fatalIf(binary.Write(&out, binary.LittleEndian, offset))
		offset += uint32(len(icon.png))
	}
	for _, icon := range icons {
		out.Write(icon.png)
	}
	return writeFile(path, out.Bytes())
}

// writeResourceObject creates the small COFF .rsrc object Go links into a
// Windows executable. Its layout is compatible with the object generated by
// common Windows resource compilers: RT_ICON entries plus one RT_GROUP_ICON.
func writeResourceObject(path string, icons []iconImage) error {
	group := makeGroupIcon(icons)
	resources := make([][]byte, 0, len(icons)+1)
	for _, icon := range icons {
		resources = append(resources, icon.png)
	}
	resources = append(resources, group)

	n := len(icons)
	dirSize := 112 + 48*n
	dataEntryStart := 96 + 32*n
	dataStart := dirSize
	dataOffsets := make([]uint32, len(resources))
	cursor := dataStart
	for i, data := range resources {
		dataOffsets[i] = uint32(cursor)
		cursor += aligned8(len(data))
	}

	var section bytes.Buffer
	writeDir(&section, 2)
	writeDirEntry(&section, 3, 0x80000000|32)
	writeDirEntry(&section, 14, 0x80000000|uint32(48+32*n))
	writeDir(&section, uint16(n))
	iconLeafBase := 48 + 8*n
	for i := range icons {
		writeDirEntry(&section, uint32(i+2), 0x80000000|uint32(iconLeafBase+i*24))
	}
	for i := range icons {
		writeDir(&section, 1)
		writeDirEntry(&section, 0x0409, uint32(dataEntryStart+i*16))
	}
	writeDir(&section, 1)
	writeDirEntry(&section, 1, 0x80000000|uint32(72+32*n))
	writeDir(&section, 1)
	writeDirEntry(&section, 0x0409, uint32(dataEntryStart+n*16))
	for i, data := range resources {
		writeU32(&section, dataOffsets[i])
		writeU32(&section, uint32(len(data)))
		writeU32(&section, 0)
		writeU32(&section, 0)
	}
	for _, data := range resources {
		section.Write(data)
		section.Write(make([]byte, aligned8(len(data))-len(data)))
	}

	raw := section.Bytes()
	relocStart := 60 + len(raw)
	symbolStart := relocStart + len(resources)*10
	var out bytes.Buffer
	// IMAGE_FILE_HEADER
	writeU16(&out, 0x8664) // AMD64
	writeU16(&out, 1)
	writeU32(&out, 0)
	writeU32(&out, uint32(symbolStart))
	writeU32(&out, 1)
	writeU16(&out, 0)
	writeU16(&out, 0x0104)
	// IMAGE_SECTION_HEADER
	out.Write([]byte{'.', 'r', 's', 'r', 'c', 0, 0, 0})
	writeU32(&out, 0)
	writeU32(&out, 0)
	writeU32(&out, uint32(len(raw)))
	writeU32(&out, 60)
	writeU32(&out, uint32(relocStart))
	writeU32(&out, 0)
	writeU16(&out, uint16(len(resources)))
	writeU16(&out, 0)
	writeU32(&out, 0x40000040)
	out.Write(raw)
	for i := range resources {
		writeU32(&out, uint32(dataEntryStart+i*16))
		writeU32(&out, 0)
		writeU16(&out, 0x0003) // IMAGE_REL_AMD64_ADDR32NB
	}
	// The section symbol used by each RVA relocation.
	out.Write([]byte{'.', 'r', 's', 'r', 'c', 0, 0, 0})
	writeU32(&out, 0)
	writeU16(&out, 1)
	writeU16(&out, 0)
	out.WriteByte(3)
	out.WriteByte(0)
	writeU32(&out, 4) // empty COFF string table
	return writeFile(path, out.Bytes())
}

func makeGroupIcon(icons []iconImage) []byte {
	var out bytes.Buffer
	writeU16(&out, 0)
	writeU16(&out, 1)
	writeU16(&out, uint16(len(icons)))
	for i, icon := range icons {
		width, height := byte(icon.size), byte(icon.size)
		if icon.size == 256 {
			width, height = 0, 0
		}
		out.WriteByte(width)
		out.WriteByte(height)
		out.WriteByte(0)
		out.WriteByte(0)
		writeU16(&out, 1)
		writeU16(&out, 32)
		writeU32(&out, uint32(len(icon.png)))
		writeU16(&out, uint16(i+2))
	}
	return out.Bytes()
}

func writeDir(out io.Writer, entries uint16) {
	writeU32(out, 0)
	writeU32(out, 0)
	writeU16(out, 0)
	writeU16(out, 0)
	writeU16(out, 0)
	writeU16(out, entries)
}

func writeDirEntry(out io.Writer, id, offset uint32) {
	writeU32(out, id)
	writeU32(out, offset)
}

func writeU16(out io.Writer, value uint16) { fatalIf(binary.Write(out, binary.LittleEndian, value)) }
func writeU32(out io.Writer, value uint32) { fatalIf(binary.Write(out, binary.LittleEndian, value)) }
func aligned8(value int) int               { return (value + 7) &^ 7 }

func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func fatalIf(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
