// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: pkg/engine/entity/replay.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerFramePB struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Team                int32                  `protobuf:"varint,3,opt,name=team,proto3" json:"team,omitempty"`
	X                   float64                `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                   float64                `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Z                   float64                `protobuf:"fixed64,6,opt,name=z,proto3" json:"z,omitempty"`
	Yaw                 float32                `protobuf:"fixed32,7,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch               float32                `protobuf:"fixed32,8,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Alive               bool                   `protobuf:"varint,9,opt,name=alive,proto3" json:"alive,omitempty"`
	Health              int32                  `protobuf:"varint,10,opt,name=health,proto3" json:"health,omitempty"`
	Armor               int32                  `protobuf:"varint,11,opt,name=armor,proto3" json:"armor,omitempty"`
	Money               int32                  `protobuf:"varint,12,opt,name=money,proto3" json:"money,omitempty"`
	HasHelmet           bool                   `protobuf:"varint,13,opt,name=has_helmet,json=hasHelmet,proto3" json:"has_helmet,omitempty"`
	HasDefuseKit        bool                   `protobuf:"varint,14,opt,name=has_defuse_kit,json=hasDefuseKit,proto3" json:"has_defuse_kit,omitempty"`
	IsScoped            bool                   `protobuf:"varint,15,opt,name=is_scoped,json=isScoped,proto3" json:"is_scoped,omitempty"`
	FlashDuration       float32                `protobuf:"fixed32,16,opt,name=flash_duration,json=flashDuration,proto3" json:"flash_duration,omitempty"`
	IsBlinded           bool                   `protobuf:"varint,17,opt,name=is_blinded,json=isBlinded,proto3" json:"is_blinded,omitempty"`
	Inventory           []int32                `protobuf:"varint,18,rep,packed,name=inventory,proto3" json:"inventory,omitempty"`
	ActiveWeapon        int32                  `protobuf:"varint,19,opt,name=active_weapon,json=activeWeapon,proto3" json:"active_weapon,omitempty"`
	Buttons             []uint64               `protobuf:"varint,20,rep,packed,name=buttons,proto3" json:"buttons,omitempty"`
	Kills               int32                  `protobuf:"varint,21,opt,name=kills,proto3" json:"kills,omitempty"`
	Assists             int32                  `protobuf:"varint,22,opt,name=assists,proto3" json:"assists,omitempty"`
	Deaths              int32                  `protobuf:"varint,23,opt,name=deaths,proto3" json:"deaths,omitempty"`
	MoneySpentTotal     int32                  `protobuf:"varint,24,opt,name=money_spent_total,json=moneySpentTotal,proto3" json:"money_spent_total,omitempty"`
	MoneySpentThisRound int32                  `protobuf:"varint,25,opt,name=money_spent_this_round,json=moneySpentThisRound,proto3" json:"money_spent_this_round,omitempty"`
	EquipmentValue      int32                  `protobuf:"varint,26,opt,name=equipment_value,json=equipmentValue,proto3" json:"equipment_value,omitempty"`
	SteamId             uint64                 `protobuf:"varint,27,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	IsBot               bool                   `protobuf:"varint,28,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlayerFramePB) Reset() {
	*x = PlayerFramePB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerFramePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFramePB) ProtoMessage() {}

func (x *PlayerFramePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFramePB.ProtoReflect.Descriptor instead.
func (*PlayerFramePB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerFramePB) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerFramePB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerFramePB) GetTeam() int32 {
	if x != nil {
		return x.Team
	}
	return 0
}

func (x *PlayerFramePB) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerFramePB) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerFramePB) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerFramePB) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerFramePB) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerFramePB) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *PlayerFramePB) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerFramePB) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *PlayerFramePB) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *PlayerFramePB) GetHasHelmet() bool {
	if x != nil {
		return x.HasHelmet
	}
	return false
}

func (x *PlayerFramePB) GetHasDefuseKit() bool {
	if x != nil {
		return x.HasDefuseKit
	}
	return false
}

func (x *PlayerFramePB) GetIsScoped() bool {
	if x != nil {
		return x.IsScoped
	}
	return false
}

func (x *PlayerFramePB) GetFlashDuration() float32 {
	if x != nil {
		return x.FlashDuration
	}
	return 0
}

func (x *PlayerFramePB) GetIsBlinded() bool {
	if x != nil {
		return x.IsBlinded
	}
	return false
}

func (x *PlayerFramePB) GetInventory() []int32 {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *PlayerFramePB) GetActiveWeapon() int32 {
	if x != nil {
		return x.ActiveWeapon
	}
	return 0
}

func (x *PlayerFramePB) GetButtons() []uint64 {
	if x != nil {
		return x.Buttons
	}
	return nil
}

func (x *PlayerFramePB) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerFramePB) GetAssists() int32 {
	if x != nil {
		return x.Assists
	}
	return 0
}

func (x *PlayerFramePB) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerFramePB) GetMoneySpentTotal() int32 {
	if x != nil {
		return x.MoneySpentTotal
	}
	return 0
}

func (x *PlayerFramePB) GetMoneySpentThisRound() int32 {
	if x != nil {
		return x.MoneySpentThisRound
	}
	return 0
}

func (x *PlayerFramePB) GetEquipmentValue() int32 {
	if x != nil {
		return x.EquipmentValue
	}
	return 0
}

func (x *PlayerFramePB) GetSteamId() uint64 {
	if x != nil {
		return x.SteamId
	}
	return 0
}

func (x *PlayerFramePB) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

type PointPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointPB) Reset() {
	*x = PointPB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointPB) ProtoMessage() {}

func (x *PointPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointPB.ProtoReflect.Descriptor instead.
func (*PointPB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{1}
}

func (x *PointPB) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PointPB) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PointPB) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ProjectileFramePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"`
	ThrowerName   string                 `protobuf:"bytes,5,opt,name=thrower_name,json=throwerName,proto3" json:"thrower_name,omitempty"`
	ThrowerId     int32                  `protobuf:"varint,6,opt,name=thrower_id,json=throwerId,proto3" json:"thrower_id,omitempty"`
	EntityId      int32                  `protobuf:"varint,7,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Trajectory    []*PointPB             `protobuf:"bytes,8,rep,name=trajectory,proto3" json:"trajectory,omitempty"`
	IsExploded    bool                   `protobuf:"varint,9,opt,name=is_exploded,json=isExploded,proto3" json:"is_exploded,omitempty"`
	Ttl           int64                  `protobuf:"varint,10,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectileFramePB) Reset() {
	*x = ProjectileFramePB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectileFramePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectileFramePB) ProtoMessage() {}

func (x *ProjectileFramePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectileFramePB.ProtoReflect.Descriptor instead.
func (*ProjectileFramePB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectileFramePB) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ProjectileFramePB) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProjectileFramePB) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ProjectileFramePB) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *ProjectileFramePB) GetThrowerName() string {
	if x != nil {
		return x.ThrowerName
	}
	return ""
}

func (x *ProjectileFramePB) GetThrowerId() int32 {
	if x != nil {
		return x.ThrowerId
	}
	return 0
}

func (x *ProjectileFramePB) GetEntityId() int32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *ProjectileFramePB) GetTrajectory() []*PointPB {
	if x != nil {
		return x.Trajectory
	}
	return nil
}

func (x *ProjectileFramePB) GetIsExploded() bool {
	if x != nil {
		return x.IsExploded
	}
	return false
}

func (x *ProjectileFramePB) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type KillEventPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KillerId      int32                  `protobuf:"varint,1,opt,name=killer_id,json=killerId,proto3" json:"killer_id,omitempty"`
	AssistantId   int32                  `protobuf:"varint,2,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	WeaponId      int32                  `protobuf:"varint,3,opt,name=weapon_id,json=weaponId,proto3" json:"weapon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillEventPB) Reset() {
	*x = KillEventPB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillEventPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillEventPB) ProtoMessage() {}

func (x *KillEventPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillEventPB.ProtoReflect.Descriptor instead.
func (*KillEventPB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{3}
}

func (x *KillEventPB) GetKillerId() int32 {
	if x != nil {
		return x.KillerId
	}
	return 0
}

func (x *KillEventPB) GetAssistantId() int32 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *KillEventPB) GetWeaponId() int32 {
	if x != nil {
		return x.WeaponId
	}
	return 0
}

type RoundTimeInfoPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	TimeRemaining float64                `protobuf:"fixed64,2,opt,name=time_remaining,json=timeRemaining,proto3" json:"time_remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundTimeInfoPB) Reset() {
	*x = RoundTimeInfoPB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundTimeInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundTimeInfoPB) ProtoMessage() {}

func (x *RoundTimeInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundTimeInfoPB.ProtoReflect.Descriptor instead.
func (*RoundTimeInfoPB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{4}
}

func (x *RoundTimeInfoPB) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RoundTimeInfoPB) GetTimeRemaining() float64 {
	if x != nil {
		return x.TimeRemaining
	}
	return 0
}

type BombFramePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	IsPlanted     bool                   `protobuf:"varint,4,opt,name=is_planted,json=isPlanted,proto3" json:"is_planted,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Site          string                 `protobuf:"bytes,6,opt,name=site,proto3" json:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BombFramePB) Reset() {
	*x = BombFramePB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BombFramePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BombFramePB) ProtoMessage() {}

func (x *BombFramePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BombFramePB.ProtoReflect.Descriptor instead.
func (*BombFramePB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{5}
}

func (x *BombFramePB) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BombFramePB) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BombFramePB) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *BombFramePB) GetIsPlanted() bool {
	if x != nil {
		return x.IsPlanted
	}
	return false
}

func (x *BombFramePB) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BombFramePB) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type DroppedEquipmentPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroppedEquipmentPB) Reset() {
	*x = DroppedEquipmentPB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroppedEquipmentPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroppedEquipmentPB) ProtoMessage() {}

func (x *DroppedEquipmentPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroppedEquipmentPB.ProtoReflect.Descriptor instead.
func (*DroppedEquipmentPB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{6}
}

func (x *DroppedEquipmentPB) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DroppedEquipmentPB) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DroppedEquipmentPB) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *DroppedEquipmentPB) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type FramePB struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	TimeMs           int64                        `protobuf:"varint,1,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	Tick             int32                        `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Round            int32                        `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	RoundTime        *RoundTimeInfoPB             `protobuf:"bytes,4,opt,name=round_time,json=roundTime,proto3" json:"round_time,omitempty"`
	Players          map[int32]*PlayerFramePB     `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SortedPlayers    []int32                      `protobuf:"varint,6,rep,packed,name=sorted_players,json=sortedPlayers,proto3" json:"sorted_players,omitempty"`
	KillEvents       map[int32]*KillEventPB       `protobuf:"bytes,7,rep,name=kill_events,json=killEvents,proto3" json:"kill_events,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Projectiles      map[int32]*ProjectileFramePB `protobuf:"bytes,8,rep,name=projectiles,proto3" json:"projectiles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SortedProjs      []int32                      `protobuf:"varint,9,rep,packed,name=sorted_projs,json=sortedProjs,proto3" json:"sorted_projs,omitempty"`
	DroppedEquipment []*DroppedEquipmentPB        `protobuf:"bytes,10,rep,name=dropped_equipment,json=droppedEquipment,proto3" json:"dropped_equipment,omitempty"`
	Bomb             *BombFramePB                 `protobuf:"bytes,11,opt,name=bomb,proto3" json:"bomb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FramePB) Reset() {
	*x = FramePB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FramePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FramePB) ProtoMessage() {}

func (x *FramePB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FramePB.ProtoReflect.Descriptor instead.
func (*FramePB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{7}
}

func (x *FramePB) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *FramePB) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *FramePB) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *FramePB) GetRoundTime() *RoundTimeInfoPB {
	if x != nil {
		return x.RoundTime
	}
	return nil
}

func (x *FramePB) GetPlayers() map[int32]*PlayerFramePB {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *FramePB) GetSortedPlayers() []int32 {
	if x != nil {
		return x.SortedPlayers
	}
	return nil
}

func (x *FramePB) GetKillEvents() map[int32]*KillEventPB {
	if x != nil {
		return x.KillEvents
	}
	return nil
}

func (x *FramePB) GetProjectiles() map[int32]*ProjectileFramePB {
	if x != nil {
		return x.Projectiles
	}
	return nil
}

func (x *FramePB) GetSortedProjs() []int32 {
	if x != nil {
		return x.SortedProjs
	}
	return nil
}

func (x *FramePB) GetDroppedEquipment() []*DroppedEquipmentPB {
	if x != nil {
		return x.DroppedEquipment
	}
	return nil
}

func (x *FramePB) GetBomb() *BombFramePB {
	if x != nil {
		return x.Bomb
	}
	return nil
}

type ProjectileRenderConfigPB struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExplosionRadius   float64                `protobuf:"fixed64,1,opt,name=explosion_radius,json=explosionRadius,proto3" json:"explosion_radius,omitempty"`
	DurationInMs      int64                  `protobuf:"varint,2,opt,name=duration_in_ms,json=durationInMs,proto3" json:"duration_in_ms,omitempty"`
	CanClearSmoke     bool                   `protobuf:"varint,3,opt,name=can_clear_smoke,json=canClearSmoke,proto3" json:"can_clear_smoke,omitempty"`
	CanExtinguishFire bool                   `protobuf:"varint,4,opt,name=can_extinguish_fire,json=canExtinguishFire,proto3" json:"can_extinguish_fire,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProjectileRenderConfigPB) Reset() {
	*x = ProjectileRenderConfigPB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectileRenderConfigPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectileRenderConfigPB) ProtoMessage() {}

func (x *ProjectileRenderConfigPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectileRenderConfigPB.ProtoReflect.Descriptor instead.
func (*ProjectileRenderConfigPB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectileRenderConfigPB) GetExplosionRadius() float64 {
	if x != nil {
		return x.ExplosionRadius
	}
	return 0
}

func (x *ProjectileRenderConfigPB) GetDurationInMs() int64 {
	if x != nil {
		return x.DurationInMs
	}
	return 0
}

func (x *ProjectileRenderConfigPB) GetCanClearSmoke() bool {
	if x != nil {
		return x.CanClearSmoke
	}
	return false
}

func (x *ProjectileRenderConfigPB) GetCanExtinguishFire() bool {
	if x != nil {
		return x.CanExtinguishFire
	}
	return false
}

type ReplayRoundPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Frames        []*FramePB             `protobuf:"bytes,3,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRoundPB) Reset() {
	*x = ReplayRoundPB{}
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRoundPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRoundPB) ProtoMessage() {}

func (x *ReplayRoundPB) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_engine_entity_replay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRoundPB.ProtoReflect.Descriptor instead.
func (*ReplayRoundPB) Descriptor() ([]byte, []int) {
	return file_pkg_engine_entity_replay_proto_rawDescGZIP(), []int{9}
}

func (x *ReplayRoundPB) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ReplayRoundPB) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ReplayRoundPB) GetFrames() []*FramePB {
	if x != nil {
		return x.Frames
	}
	return nil
}

var File_pkg_engine_entity_replay_proto protoreflect.FileDescriptor

const file_pkg_engine_entity_replay_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/engine/entity/replay.proto\x12\x06entity\"\xfc\x05\n" +
	"\rPlayerFramePB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04team\x18\x03 \x01(\x05R\x04team\x12\f\n" +
	"\x01x\x18\x04 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x06 \x01(\x01R\x01z\x12\x10\n" +
	"\x03yaw\x18\a \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\b \x01(\x02R\x05pitch\x12\x14\n" +
	"\x05alive\x18\t \x01(\bR\x05alive\x12\x16\n" +
	"\x06health\x18\n" +
	" \x01(\x05R\x06health\x12\x14\n" +
	"\x05armor\x18\v \x01(\x05R\x05armor\x12\x14\n" +
	"\x05money\x18\f \x01(\x05R\x05money\x12\x1d\n" +
	"\n" +
	"has_helmet\x18\r \x01(\bR\thasHelmet\x12$\n" +
	"\x0ehas_defuse_kit\x18\x0e \x01(\bR\fhasDefuseKit\x12\x1b\n" +
	"\tis_scoped\x18\x0f \x01(\bR\bisScoped\x12%\n" +
	"\x0eflash_duration\x18\x10 \x01(\x02R\rflashDuration\x12\x1d\n" +
	"\n" +
	"is_blinded\x18\x11 \x01(\bR\tisBlinded\x12\x1c\n" +
	"\tinventory\x18\x12 \x03(\x05R\tinventory\x12#\n" +
	"\ractive_weapon\x18\x13 \x01(\x05R\factiveWeapon\x12\x18\n" +
	"\abuttons\x18\x14 \x03(\x04R\abuttons\x12\x14\n" +
	"\x05kills\x18\x15 \x01(\x05R\x05kills\x12\x18\n" +
	"\aassists\x18\x16 \x01(\x05R\aassists\x12\x16\n" +
	"\x06deaths\x18\x17 \x01(\x05R\x06deaths\x12*\n" +
	"\x11money_spent_total\x18\x18 \x01(\x05R\x0fmoneySpentTotal\x123\n" +
	"\x16money_spent_this_round\x18\x19 \x01(\x05R\x13moneySpentThisRound\x12'\n" +
	"\x0fequipment_value\x18\x1a \x01(\x05R\x0eequipmentValue\x12\x19\n" +
	"\bsteam_id\x18\x1b \x01(\x04R\asteamId\x12\x15\n" +
	"\x06is_bot\x18\x1c \x01(\bR\x05isBot\"3\n" +
	"\aPointPB\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"\x94\x02\n" +
	"\x11ProjectileFramePB\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x01R\x01z\x12!\n" +
	"\fthrower_name\x18\x05 \x01(\tR\vthrowerName\x12\x1d\n" +
	"\n" +
	"thrower_id\x18\x06 \x01(\x05R\tthrowerId\x12\x1b\n" +
	"\tentity_id\x18\a \x01(\x05R\bentityId\x12/\n" +
	"\n" +
	"trajectory\x18\b \x03(\v2\x0f.entity.PointPBR\n" +
	"trajectory\x12\x1f\n" +
	"\vis_exploded\x18\t \x01(\bR\n" +
	"isExploded\x12\x10\n" +
	"\x03ttl\x18\n" +
	" \x01(\x03R\x03ttl\"j\n" +
	"\vKillEventPB\x12\x1b\n" +
	"\tkiller_id\x18\x01 \x01(\x05R\bkillerId\x12!\n" +
	"\fassistant_id\x18\x02 \x01(\x05R\vassistantId\x12\x1b\n" +
	"\tweapon_id\x18\x03 \x01(\x05R\bweaponId\"N\n" +
	"\x0fRoundTimeInfoPB\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12%\n" +
	"\x0etime_remaining\x18\x02 \x01(\x01R\rtimeRemaining\"\x80\x01\n" +
	"\vBombFramePB\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\x12\x1d\n" +
	"\n" +
	"is_planted\x18\x04 \x01(\bR\tisPlanted\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x12\n" +
	"\x04site\x18\x06 \x01(\tR\x04site\"R\n" +
	"\x12DroppedEquipmentPB\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x01R\x01z\"\x80\x06\n" +
	"\aFramePB\x12\x17\n" +
	"\atime_ms\x18\x01 \x01(\x03R\x06timeMs\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x05R\x04tick\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x126\n" +
	"\n" +
	"round_time\x18\x04 \x01(\v2\x17.entity.RoundTimeInfoPBR\troundTime\x126\n" +
	"\aplayers\x18\x05 \x03(\v2\x1c.entity.FramePB.PlayersEntryR\aplayers\x12%\n" +
	"\x0esorted_players\x18\x06 \x03(\x05R\rsortedPlayers\x12@\n" +
	"\vkill_events\x18\a \x03(\v2\x1f.entity.FramePB.KillEventsEntryR\n" +
	"killEvents\x12B\n" +
	"\vprojectiles\x18\b \x03(\v2 .entity.FramePB.ProjectilesEntryR\vprojectiles\x12!\n" +
	"\fsorted_projs\x18\t \x03(\x05R\vsortedProjs\x12G\n" +
	"\x11dropped_equipment\x18\n" +
	" \x03(\v2\x1a.entity.DroppedEquipmentPBR\x10droppedEquipment\x12'\n" +
	"\x04bomb\x18\v \x01(\v2\x13.entity.BombFramePBR\x04bomb\x1aQ\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.entity.PlayerFramePBR\x05value:\x028\x01\x1aR\n" +
	"\x0fKillEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.entity.KillEventPBR\x05value:\x028\x01\x1aY\n" +
	"\x10ProjectilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.entity.ProjectileFramePBR\x05value:\x028\x01\"\xc3\x01\n" +
	"\x18ProjectileRenderConfigPB\x12)\n" +
	"\x10explosion_radius\x18\x01 \x01(\x01R\x0fexplosionRadius\x12$\n" +
	"\x0eduration_in_ms\x18\x02 \x01(\x03R\fdurationInMs\x12&\n" +
	"\x0fcan_clear_smoke\x18\x03 \x01(\bR\rcanClearSmoke\x12.\n" +
	"\x13can_extinguish_fire\x18\x04 \x01(\bR\x11canExtinguishFire\"b\n" +
	"\rReplayRoundPB\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x12'\n" +
	"\x06frames\x18\x03 \x03(\v2\x0f.entity.FramePBR\x06framesB4Z2github.com/bugkingzht/cs-demobox/pkg/engine/entityb\x06proto3"

var (
	file_pkg_engine_entity_replay_proto_rawDescOnce sync.Once
	file_pkg_engine_entity_replay_proto_rawDescData []byte
)

func file_pkg_engine_entity_replay_proto_rawDescGZIP() []byte {
	file_pkg_engine_entity_replay_proto_rawDescOnce.Do(func() {
		file_pkg_engine_entity_replay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_engine_entity_replay_proto_rawDesc), len(file_pkg_engine_entity_replay_proto_rawDesc)))
	})
	return file_pkg_engine_entity_replay_proto_rawDescData
}

var file_pkg_engine_entity_replay_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_engine_entity_replay_proto_goTypes = []any{
	(*PlayerFramePB)(nil),            // 0: entity.PlayerFramePB
	(*PointPB)(nil),                  // 1: entity.PointPB
	(*ProjectileFramePB)(nil),        // 2: entity.ProjectileFramePB
	(*KillEventPB)(nil),              // 3: entity.KillEventPB
	(*RoundTimeInfoPB)(nil),          // 4: entity.RoundTimeInfoPB
	(*BombFramePB)(nil),              // 5: entity.BombFramePB
	(*DroppedEquipmentPB)(nil),       // 6: entity.DroppedEquipmentPB
	(*FramePB)(nil),                  // 7: entity.FramePB
	(*ProjectileRenderConfigPB)(nil), // 8: entity.ProjectileRenderConfigPB
	(*ReplayRoundPB)(nil),            // 9: entity.ReplayRoundPB
	nil,                              // 10: entity.FramePB.PlayersEntry
	nil,                              // 11: entity.FramePB.KillEventsEntry
	nil,                              // 12: entity.FramePB.ProjectilesEntry
}
var file_pkg_engine_entity_replay_proto_depIdxs = []int32{
	1,  // 0: entity.ProjectileFramePB.trajectory:type_name -> entity.PointPB
	4,  // 1: entity.FramePB.round_time:type_name -> entity.RoundTimeInfoPB
	10, // 2: entity.FramePB.players:type_name -> entity.FramePB.PlayersEntry
	11, // 3: entity.FramePB.kill_events:type_name -> entity.FramePB.KillEventsEntry
	12, // 4: entity.FramePB.projectiles:type_name -> entity.FramePB.ProjectilesEntry
	6,  // 5: entity.FramePB.dropped_equipment:type_name -> entity.DroppedEquipmentPB
	5,  // 6: entity.FramePB.bomb:type_name -> entity.BombFramePB
	7,  // 7: entity.ReplayRoundPB.frames:type_name -> entity.FramePB
	0,  // 8: entity.FramePB.PlayersEntry.value:type_name -> entity.PlayerFramePB
	3,  // 9: entity.FramePB.KillEventsEntry.value:type_name -> entity.KillEventPB
	2,  // 10: entity.FramePB.ProjectilesEntry.value:type_name -> entity.ProjectileFramePB
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_engine_entity_replay_proto_init() }
func file_pkg_engine_entity_replay_proto_init() {
	if File_pkg_engine_entity_replay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_engine_entity_replay_proto_rawDesc), len(file_pkg_engine_entity_replay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_engine_entity_replay_proto_goTypes,
		DependencyIndexes: file_pkg_engine_entity_replay_proto_depIdxs,
		MessageInfos:      file_pkg_engine_entity_replay_proto_msgTypes,
	}.Build()
	File_pkg_engine_entity_replay_proto = out.File
	file_pkg_engine_entity_replay_proto_goTypes = nil
	file_pkg_engine_entity_replay_proto_depIdxs = nil
}
